apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: stratum-ns
  labels:
    {{- include "stratum-backend-chart.labels" . | nindent 4 }}
spec:
  selector:
    app: stratum-backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}